# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-lb
spec:
  clusterIP: None
  selector:
    app: postgresql-db
  ports:
    - port: 5432
      targetPort: 5432